Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 1088
      Handler: iot.lambdaFunctions.RegisterDeviceController
      CodeUri: /Users/sagarkpr/IdeaProjects/HelloWorldFunction
      Runtime: java11
      Architectures:
        - x86_64